apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - image: koraichi/nginx_demo:0.3
        name: main
        ports:
        - containerPort: 80
          protocol: "TCP"
          name: main
        livenessProbe:
          httpGet:
            port: 80
            scheme: "HTTP"
        readinessProbe:
          httpGet:
            port: 80
            scheme: "HTTP"
        resources:
          limits:
            cpu: 10m
            memory: "50Mi"
          requests:
            cpu: 1m
            memory: "10Mi"
                
